// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVojdAtcZWi_Fdk0eqmcQqidjQ4Dlk4P8',
    appId: '1:839541775531:web:3342810d9d67d20f742bee',
    messagingSenderId: '839541775531',
    projectId: 'notificationtest-10506',
    authDomain: 'notificationtest-10506.firebaseapp.com',
    storageBucket: 'notificationtest-10506.appspot.com',
    measurementId: 'G-PZWB3EB3NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQixCgV-rjjKid7hjQk62xZ_t2M2pTweU',
    appId: '1:839541775531:android:b79edc58e6137307742bee',
    messagingSenderId: '839541775531',
    projectId: 'notificationtest-10506',
    storageBucket: 'notificationtest-10506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUyB0YHGKcwBlqMuSSh1dOBAESXlDgdE',
    appId: '1:839541775531:ios:d2187cc51beaac1e742bee',
    messagingSenderId: '839541775531',
    projectId: 'notificationtest-10506',
    storageBucket: 'notificationtest-10506.appspot.com',
    iosClientId: '839541775531-bdca5mejpm4v8ch3bf980aa763k4712o.apps.googleusercontent.com',
    iosBundleId: 'com.vidhan.notificationTest',
  );
}
